### ISSUE TITLE
build / start not working

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/livemark#81]
Hi @roll! I am going through the docs and am getting errors when trying to build / start the site.

First, I created a new project without an index.md and got errors, and I also tried it after creating an index.md file and got the same errors. Here are the errors:

 `livemark build`: 
`'str' object has no attribute 'setdefault'`

I also tried `livemark start` & got an error:
`AttributeError: 'str' object has no attribute 'copy'`

Then, I tried building the site from this repo and also got errors. 

`livemark build`:
`to_snap() got an unexpected keyword argument 'json'`

and 

`livemark start`: 
`TypeError: to_snap() got an unexpected keyword argument 'json'`

I'm on Python 3.8 & Livemark 0.39.0

Any ideas? Thanks!

**Comment by roll** [comment]
Hi @lwinfree,

Please try:
```
pip install --upgrade frictionless
pip install --upgrade livemark
```

I think it's fixed now

**Comment by lwinfree** [comment]
@roll I'm still getting an error (although it is different now!)

`livemark build` :     
`[Errno 2] No such file or directory: '/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/livemark/plugins/table/markup.html'`

`livemark start` : 
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/livemark/plugins/table/markup.html'`

This is after upgrading both frictionless (v 4.16.2) & livemark (v 0.44), and within the livemark directory (which I just did a git pull on, so it is updated too)

**Comment by roll** [comment]
@lwinfree 
It seems that something is wrong with the virtualenv.

It's anyway better to try in a new directory (not a livemark one) so it will be closer to a new user.
